name: Android CI

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: check file
      run: ls ./app/build/outputs/apk/debug/app-debug.apk
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: orali-money.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
